### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIn0sImlhdCI6MTY1MTcxNDUwNSwiZXhwIjoxNjUxNzE4MTA1fQ.e9m1gzOWa82rpj7XLBy4uLfj8w4JqnIjhBBKNpE3byo

{
    "firstName": "Xiao",
    "lastName": "ting",
    "email": "admin4@gmail.com",
    "password": "admin",
    "role": "ADMIN"
}


### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{    
    "email": "admin@gmail.com",
    "password": "admin"
}


### Get image
GET http://localhost:3000/api/user/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIn0sImlhdCI6MTY1MTc1MTA3NywiZXhwIjoxNjUxNzU0Njc3fQ.N277eJkFFkWP9ZxnuzxVNFh2ocvY2VJG5wk0wOFQDjI