### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName": "Xiao",
    "lastName": "ting",
    "email": "admin4@gmail.com",
    "password": "admin",
    "role": "ADMIN"
}


### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{    
    "email": "admin2@gmail.com",
    "password": "admin"
}


### find by id
GET  http://localhost:3000/api/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJmaXJzdE5hbWUiOiJNaW4iLCJsYXN0TmFtZSI6Ikplb25nIiwiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIifSwiaWF0IjoxNjUxODE2ODc4LCJleHAiOjE2NTE4MjA0Nzh9.DC6qFqfomECP6p04c_33b8Iqkqsw6DCoGqzPdrKYPgM

### Get Actual image
GET http://localhost:3000/api/user/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJmaXJzdE5hbWUiOiJNaW4iLCJsYXN0TmFtZSI6Ikplb25nIiwiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIifSwiaWF0IjoxNjUxOTI4OTExLCJleHAiOjE2NTE5MzI1MTF9.TxyLYL03iy011T2e1qKVUJqE16pUIot4M-9d0E9fEN4


### Get image name
GET http://localhost:3000/api/user/image-name
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJmaXJzdE5hbWUiOiJNaW4iLCJsYXN0TmFtZSI6Ikplb25nIiwiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIifSwiaWF0IjoxNjUxOTI4OTExLCJleHAiOjE2NTE5MzI1MTF9.TxyLYL03iy011T2e1qKVUJqE16pUIot4M-9d0E9fEN4